"""empty message

Revision ID: 40b04cc6d75d
Revises: 948b3f1838ee
Create Date: 2020-01-03 10:55:30.075659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b04cc6d75d'
down_revision = '948b3f1838ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_user', sa.Column('password_hash', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_user', 'password_hash')
    # ### end Alembic commands ###
