"""empty message

Revision ID: 948b3f1838ee
Revises: 
Create Date: 2020-01-03 10:47:13.375014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948b3f1838ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_itemtype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['tbl_itemtype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_province',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_activate', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('tbl_itemplan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('item_type', sa.Integer(), nullable=False),
    sa.Column('applicant', sa.Integer(), nullable=False),
    sa.Column('province', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('estimate_start_time', sa.DateTime(), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('estimate_end_time', sa.DateTime(), nullable=False),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('general_budget', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('WAIT_CHECK', 'PASS', 'REJECTED', 'CANCELED'), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('commit', sa.Boolean(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('review', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['applicant'], ['tbl_user.id'], ),
    sa.ForeignKeyConstraint(['item_type'], ['tbl_itemtype.id'], ),
    sa.ForeignKeyConstraint(['province'], ['tbl_province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_itemplan_status'), 'tbl_itemplan', ['status'], unique=False)
    op.create_table('tbl_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('itemplans', sa.Integer(), nullable=False),
    sa.Column('check_person', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('WAIT_CHECK', 'PASS', 'REJECTED', 'CANCELED'), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('commit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['check_person'], ['tbl_user.id'], ),
    sa.ForeignKeyConstraint(['itemplans'], ['tbl_itemplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_check_result'), 'tbl_check', ['result'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_check_result'), table_name='tbl_check')
    op.drop_table('tbl_check')
    op.drop_index(op.f('ix_tbl_itemplan_status'), table_name='tbl_itemplan')
    op.drop_table('tbl_itemplan')
    op.drop_table('tbl_user')
    op.drop_table('tbl_province')
    op.drop_table('tbl_itemtype')
    # ### end Alembic commands ###
