"""empty message

Revision ID: c6c3fbc2f73c
Revises: 8327e8191319
Create Date: 2020-01-02 09:39:29.026383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c3fbc2f73c'
down_revision = '8327e8191319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_check', sa.Column('commit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_check', 'commit')
    # ### end Alembic commands ###
